# TOTAL PAYLOAD SIZE
PAYLOAD_LENGTH = 4
# SIZE OF THE PAYLOAD IDENTIFIER
PAYLOAD_NAME_LENGTH = 4
# SIZE OF SEGMENTS HEADER
SEGMENTS_LENGTH = 4
# SIZE OF JSON PAYLOAD
JSON_LENGTH = 4
# The order of the bytes from the stream little or big
BYTE_ORDER = "big"
# Encoding for strings
ENCODING = "UTF-8"